name: 'test'
on:
  push:

jobs:
  test:
    name: nvim_rs_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: apt-get update && apt-get install -y neovim
      - run: cargo test --all-features
